# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0016_remove_soldier_is_baknaz_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerecord',
            name='soldier_name',
            field=models.CharField(default='ah sheli', max_length=250),
        ),
    ]
